"""

Revision ID: 25da07e7df81
Revises: 60912991d4f8
Create Date: 2025-03-26 04:16:22.746246

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '25da07e7df81'
down_revision = '60912991d4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dropoffpoint', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('dropoffpoint', sa.Column('longitude', sa.Float(), nullable=True))
    op.alter_column('dropoffpoint', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dropoffpoint', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('dropoffpoint', 'longitude')
    op.drop_column('dropoffpoint', 'latitude')
    # ### end Alembic commands ###
