"""add is_done to drop_off_point

Revision ID: 36e3a0a05cf1
Revises: f7de84082f44
Create Date: 2025-03-28 03:08:05.207447

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '36e3a0a05cf1'
down_revision = 'f7de84082f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dropoffpoint', sa.Column('is_done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dropoffpoint', 'is_done')
    # ### end Alembic commands ###
