"""add responsible link

Revision ID: f7de84082f44
Revises: 0c0be9e258b6
Create Date: 2025-03-27 23:01:03.950144

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f7de84082f44'
down_revision = '0c0be9e258b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dropoffpoint', sa.Column('responsible_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'dropoffpoint', 'memberof', ['responsible_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('memberof_member_id_fkey', 'memberof', type_='foreignkey')
    op.drop_constraint('memberof_organization_id_fkey', 'memberof', type_='foreignkey')
    op.create_foreign_key(None, 'memberof', 'user', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'memberof', 'user', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memberof', type_='foreignkey')
    op.drop_constraint(None, 'memberof', type_='foreignkey')
    op.create_foreign_key('memberof_organization_id_fkey', 'memberof', 'user', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('memberof_member_id_fkey', 'memberof', 'user', ['member_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'dropoffpoint', type_='foreignkey')
    op.drop_column('dropoffpoint', 'responsible_id')
    # ### end Alembic commands ###
